/* ide.c — hosted PicoScript IDE, served straight out of the picoweb
 * executable. See ide.h for the protocol; see src/ide_assets.h for the
 * compiled-in HTML/JS asset declarations (generated by
 * tools/gen_ide_assets.py from the vendored ../picoscript/docs/index.html
 * + tools/ide_server_bridge.js, tools/ide_picowal_workspace.html, and the
 * sibling picoscript/vm/pico_hooks.js, picoc.js, picovm.js). */

#include "ide.h"
#include "ide_assets.h"
#include "security_headers.h"
#include "picowal_partition.h"
#include "static_pack.h"
#include "pico_route.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>

static char   g_prefix[64] = {0};
static size_t g_prefix_len = 0;
static bool   g_enabled = false;

bool ide_enabled(void) { return g_enabled; }

static bool valid_prefix(const char* prefix, size_t cap) {
    size_t pl = prefix ? strlen(prefix) : 0;
    if (pl < 2 || pl >= cap) {
        fprintf(stderr, "ide: invalid --ide-prefix (must be 2..%zu chars, start and end with '/')\n", cap - 1);
        return false;
    }
    if (prefix[0] != '/' || prefix[pl - 1] != '/') {
        fprintf(stderr, "ide: invalid --ide-prefix '%s' (must start and end with '/')\n", prefix);
        return false;
    }
    return true;
}

bool ide_init(const char* prefix) {
    g_enabled = false;
    if (!api_picowal_db()) {
        fprintf(stderr, "ide: requires --picowal-device to be configured first\n");
        return false;
    }
    if (!valid_prefix(prefix, sizeof(g_prefix))) return false;
    size_t pl = strlen(prefix);
    memcpy(g_prefix, prefix, pl + 1);
    g_prefix_len = pl;
    g_enabled = true;
    return true;
}

bool ide_path_matches(const char* path, size_t path_len) {
    return g_enabled &&
           path_len >= g_prefix_len &&
           memcmp(path, g_prefix, g_prefix_len) == 0;
}

/* ----- response helpers ----- */

static void resp_status_only(api_resp_t* r, int status, const char* reason) {
    r->status = status;
    r->head_len = (size_t)snprintf(r->head, sizeof(r->head),
                                   "HTTP/1.1 %d %s\r\n"
                                   "Server: picoweb\r\n"
                                   "Content-Length: 0\r\n"
                                   PICOWEB_SECURITY_HEADERS
                                   "Cache-Control: no-store\r\n",
                                   status, reason);
}

static void resp_text_error(api_resp_t* r, int status, const char* reason, const char* body) {
    size_t blen = body ? strlen(body) : 0;
    r->status = status;
    r->head_len = (size_t)snprintf(r->head, sizeof(r->head),
                                   "HTTP/1.1 %d %s\r\n"
                                   "Server: picoweb\r\n"
                                   "Content-Type: text/plain; charset=utf-8\r\n"
                                   "Content-Length: %zu\r\n"
                                   PICOWEB_SECURITY_HEADERS
                                   "Cache-Control: no-store\r\n",
                                   status, reason, blen);
    if (blen) {
        r->body = (char*)malloc(blen);
        if (r->body) {
            memcpy(r->body, body, blen);
            r->body_len = blen;
            r->body_owned = true;
        }
    }
}

/* Serves a compiled-in, statically-allocated asset (never heap-owned --
 * body_owned stays false so api_resp_release() never frees it). */
static void resp_asset(api_resp_t* r, const char* mime,
                       const char* data, size_t len, bool head_only) {
    r->status = 200;
    r->head_len = (size_t)snprintf(r->head, sizeof(r->head),
                                   "HTTP/1.1 200 OK\r\n"
                                   "Server: picoweb\r\n"
                                   "Content-Type: %s\r\n"
                                   "Content-Length: %zu\r\n"
                                   PICOWEB_SECURITY_HEADERS
                                   "Cache-Control: no-cache\r\n",
                                   mime, len);
    if (head_only) return;
    r->body = (char*)data;
    r->body_len = len;
    r->body_owned = false;
}

/* The IDE HTML page needs a relaxed Content-Security-Policy: it fetches
 * the operator-configured (--picosts-issuer), and thus not known at
 * compile time, external PicoSTS authority's /authorize, /token and
 * /userinfo endpoints directly from the browser for the Authorization
 * Code + PKCE flow, which the default connect-src 'self' would block.
 * script-src/style-src already allow https://cdn.jsdelivr.net (for
 * Monaco) under the default policy, so only connect-src (and worker-src,
 * for Monaco's optional web-worker tokenizer) need broadening here; every
 * other route keeps the strict default PICOWEB_SECURITY_HEADERS.
 *
 * Shared by both compiled-in HTML pages (the vendored WebIDE portal and
 * the PicoWAL workspace), parameterized on `embeddable`: the portal
 * (IDE_HTML) is never framed by anything, so it keeps the strict
 * frame-ancestors 'none'/X-Frame-Options: DENY default. The PicoWAL
 * workspace (IDE_PICOWAL_HTML) IS framed -- by the portal's own top-level
 * PicoWAL tab, via a same-origin <iframe src="picowal.html"> -- so it
 * needs frame-ancestors 'self' (and X-Frame-Options: SAMEORIGIN, for
 * older browsers that only honor the legacy header) instead, while still
 * refusing to be framed cross-origin. */
static void resp_ide_like_html(api_resp_t* r, const char* data, size_t len, bool embeddable, bool head_only) {
    r->status = 200;
    r->head_len = (size_t)snprintf(r->head, sizeof(r->head),
                                   "HTTP/1.1 200 OK\r\n"
                                   "Server: picoweb\r\n"
                                   "Content-Type: text/html; charset=utf-8\r\n"
                                   "Content-Length: %zu\r\n"
                                   "X-Content-Type-Options: nosniff\r\n"
                                   "X-Frame-Options: %s\r\n"
                                   "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\n"
                                   "Content-Security-Policy: default-src 'self'; "
                                   "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
                                   "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
                                   "img-src 'self' data:; font-src 'self' data: https://cdn.jsdelivr.net; "
                                   "worker-src 'self' blob:; connect-src 'self' https: http:; "
                                   "base-uri 'none'; frame-ancestors %s; form-action 'self'\r\n"
                                   "Referrer-Policy: strict-origin-when-cross-origin\r\n"
                                   "Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()\r\n"
                                   "Cache-Control: no-cache\r\n",
                                   len,
                                   embeddable ? "SAMEORIGIN" : "DENY",
                                   embeddable ? "'self'" : "'none'");
    if (head_only) return;
    r->body = (char*)data;
    r->body_len = len;
    r->body_owned = false;
}

static void resp_ide_html(api_resp_t* r, bool head_only) {
    resp_ide_like_html(r, IDE_HTML, IDE_HTML_LEN, false, head_only);
}

static void resp_ide_picowal_html(api_resp_t* r, bool head_only) {
    resp_ide_like_html(r, IDE_PICOWAL_HTML, IDE_PICOWAL_HTML_LEN, true, head_only);
}

static void resp_json_owned(api_resp_t* r, char* body, size_t blen, bool head_only) {
    r->status = 200;
    r->head_len = (size_t)snprintf(r->head, sizeof(r->head),
                                   "HTTP/1.1 200 OK\r\n"
                                   "Server: picoweb\r\n"
                                   "Content-Type: application/json; charset=utf-8\r\n"
                                   "Content-Length: %zu\r\n"
                                   PICOWEB_SECURITY_HEADERS
                                   "Cache-Control: no-store\r\n",
                                   blen);
    if (head_only) { free(body); return; }
    r->body = body;
    r->body_len = blen;
    r->body_owned = true;
}

/* ----- /ide/config ----- */

static void dispatch_config(http_method_t method, api_resp_t* resp) {
    if (method != M_GET && method != M_HEAD) {
        resp_status_only(resp, 405, "Method Not Allowed");
        return;
    }
    char buf[1024];
    int n = snprintf(buf, sizeof(buf),
                     "{"
                     "\"ide_prefix\":\"%s\","
                     "\"wal_prefix\":\"%s\","
                     "\"static_prefix\":\"%s\","
                     "\"code_prefix\":\"%s\","
                     "\"picosts_enabled\":%s,"
                     "\"picosts_issuer\":\"%s\","
                     "\"picosts_client_id\":\"%s\","
                     "\"picosts_audience\":\"%s\""
                     "}",
                     g_prefix,
                     api_picowal_prefix(),
                     static_pack_prefix(),
                     pico_route_prefix(),
                     api_picosts_enabled() ? "true" : "false",
                     api_picosts_issuer(),
                     api_picosts_client_id(),
                     api_picosts_audience());
    if (n <= 0 || (size_t)n >= sizeof(buf)) {
        resp_text_error(resp, 500, "Internal Server Error", "config encode failed\n");
        return;
    }
    char* out = (char*)malloc((size_t)n);
    if (!out) {
        resp_text_error(resp, 500, "Internal Server Error", "oom\n");
        return;
    }
    memcpy(out, buf, (size_t)n);
    resp_json_owned(resp, out, (size_t)n, method == M_HEAD);
}

/* ----- /ide/card/{pack}/{record} ----- */

static bool parse_u32_dec(const char* s, size_t n, uint32_t max, uint32_t* out) {
    if (!s || n == 0 || !out) return false;
    uint64_t v = 0;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c < '0' || c > '9') return false;
        v = v * 10u + (uint64_t)(c - '0');
        if (v > max) return false;
    }
    *out = (uint32_t)v;
    return true;
}

/* Parses "{pack}/{record}" (no trailing filename -- unlike static_pack,
 * this is a raw KV store, not something MIME-sniffed). */
static bool parse_card_path(const char* rest, size_t rest_len,
                            uint32_t* out_pack, uint32_t* out_record) {
    const char* slash = memchr(rest, '/', rest_len);
    if (!slash) return false;
    size_t pack_len = (size_t)(slash - rest);
    size_t rec_len = rest_len - pack_len - 1;
    if (memchr(slash + 1, '/', rec_len)) return false; /* no extra segments */
    return parse_u32_dec(rest, pack_len, PICOWAL_CARD_MAX, out_pack) &&
           parse_u32_dec(slash + 1, rec_len, PICOWAL_RECORD_MAX, out_record);
}

static void dispatch_card(http_method_t method,
                         const char* path, size_t path_len,
                         const char* rest, size_t rest_len,
                         const char* body, size_t body_len,
                         const char* cookie, size_t cookie_len,
                         bool has_pw_auth_header,
                         const char* write_token, size_t write_token_len,
                         const char* tenant_id, size_t tenant_id_len,
                         bool is_partition_hop,
                         api_resp_t* resp) {
    if (method != M_GET && method != M_HEAD && method != M_PUT && method != M_DELETE) {
        resp_status_only(resp, 405, "Method Not Allowed");
        return;
    }
    uint32_t pack = 0, record = 0;
    if (!parse_card_path(rest, rest_len, &pack, &record)) {
        resp_text_error(resp, 400, "Bad Request", "expected /card/{pack}/{record}\n");
        return;
    }
    uint32_t key;
    if (!picowal_db_pack_key((uint16_t)pack, record, &key)) {
        resp_text_error(resp, 400, "Bad Request", "pack/record out of range\n");
        return;
    }

    /* Always authenticated -- unlike static_pack's public GET, the IDE
     * raw card store holds private PicoScript source / bundle drafts, so
     * every method (including reads) requires credentials. */
    if (!api_require_pw_auth(cookie, cookie_len, has_pw_auth_header,
                             write_token, write_token_len, resp)) return;

    /* Partition-aware forwarding for ALL of GET/HEAD/PUT/DELETE: the IDE
     * card store is sharded the same way static content is (each node's
     * picowal volume is its own shard, not assumed replicated), using the
     * request's tenant context to resolve ownership so reads and writes
     * work through any node in the cluster. */
    if (!is_partition_hop && picowal_partition_enabled()) {
        uint32_t vpart = picowal_partition_of_key(key);
        char owner[PICOWAL_PARTITION_NODE_ID_MAX];
        if (picowal_partition_owner(tenant_id, tenant_id_len, vpart, owner, sizeof(owner)) &&
            !picowal_partition_owner_is_self(owner)) {
            if (picowal_partition_mode_is_proxy()) {
                picowal_partition_proxy(owner, vpart, method, path, path_len,
                                        body, body_len,
                                        write_token, write_token_len,
                                        cookie, cookie_len, resp);
            } else {
                picowal_partition_redirect(owner, vpart, path, path_len, resp);
            }
            return;
        }
    }

    picowal_db_t* db = api_picowal_db();

    if (method == M_PUT) {
        if (body_len == 0 || body_len > PICOWAL_DATA_MAX) {
            resp_status_only(resp, 413, "Payload Too Large");
            return;
        }
        if (picowal_db_put_key(db, key, body, (uint32_t)body_len, false) != 0) {
            if (errno == EROFS) {
                resp_text_error(resp, 503, "Service Unavailable", "read replica: writes must go to the primary\n");
                return;
            }
            if (errno == ENOSPC) {
                resp_text_error(resp, 507, "Insufficient Storage", "wal volume full\n");
                return;
            }
            resp_text_error(resp, 500, "Internal Server Error", "ide card write failed\n");
            return;
        }
        resp_status_only(resp, 204, "No Content");
        return;
    }

    if (method == M_DELETE) {
        if (picowal_db_delete_key(db, key) != 0) {
            if (errno == EROFS) {
                resp_text_error(resp, 503, "Service Unavailable", "read replica: writes must go to the primary\n");
                return;
            }
            if (errno == ENOENT) { resp_status_only(resp, 404, "Not Found"); return; }
            resp_text_error(resp, 500, "Internal Server Error", "ide card delete failed\n");
            return;
        }
        resp_status_only(resp, 204, "No Content");
        return;
    }

    /* GET / HEAD */
    char* buf = (char*)malloc(PICOWAL_DATA_MAX);
    if (!buf) { resp_text_error(resp, 500, "Internal Server Error", "oom\n"); return; }
    int n = picowal_db_get_key(db, key, buf, PICOWAL_DATA_MAX);
    if (n < 0) { free(buf); resp_status_only(resp, 404, "Not Found"); return; }

    resp->status = 200;
    resp->head_len = (size_t)snprintf(resp->head, sizeof(resp->head),
                                      "HTTP/1.1 200 OK\r\n"
                                      "Server: picoweb\r\n"
                                      "Content-Type: application/octet-stream\r\n"
                                      "Content-Length: %d\r\n"
                                      PICOWEB_SECURITY_HEADERS
                                      "Cache-Control: no-store\r\n",
                                      n);
    if (method == M_HEAD) { free(buf); return; }
    resp->body = buf;
    resp->body_len = (size_t)n;
    resp->body_owned = true;
}

/* ----- dispatcher ----- */

void ide_dispatch(http_method_t method,
                  const char* path, size_t path_len,
                  const char* body, size_t body_len,
                  const char* cookie, size_t cookie_len,
                  bool has_pw_auth_header,
                  const char* write_token, size_t write_token_len,
                  const char* tenant_id, size_t tenant_id_len,
                  bool is_partition_hop,
                  api_resp_t* resp) {
    if (method == M_OPTIONS) {
        resp_status_only(resp, 204, "No Content");
        return;
    }

    const char* rest = path + g_prefix_len;
    size_t rest_len = path_len - g_prefix_len;

    if (rest_len == 0 || (rest_len == 10 && memcmp(rest, "index.html", 10) == 0)) {
        if (method != M_GET && method != M_HEAD) { resp_status_only(resp, 405, "Method Not Allowed"); return; }
        resp_ide_html(resp, method == M_HEAD);
        return;
    }
    if (rest_len == 12 && memcmp(rest, "picowal.html", 12) == 0) {
        if (method != M_GET && method != M_HEAD) { resp_status_only(resp, 405, "Method Not Allowed"); return; }
        resp_ide_picowal_html(resp, method == M_HEAD);
        return;
    }
    if (rest_len == 13 && memcmp(rest, "pico_hooks.js", 13) == 0) {
        if (method != M_GET && method != M_HEAD) { resp_status_only(resp, 405, "Method Not Allowed"); return; }
        resp_asset(resp, "application/javascript; charset=utf-8", IDE_PICO_HOOKS_JS, IDE_PICO_HOOKS_JS_LEN, method == M_HEAD);
        return;
    }
    if (rest_len == 8 && memcmp(rest, "picoc.js", 8) == 0) {
        if (method != M_GET && method != M_HEAD) { resp_status_only(resp, 405, "Method Not Allowed"); return; }
        resp_asset(resp, "application/javascript; charset=utf-8", IDE_PICOC_JS, IDE_PICOC_JS_LEN, method == M_HEAD);
        return;
    }
    if (rest_len == 9 && memcmp(rest, "picovm.js", 9) == 0) {
        if (method != M_GET && method != M_HEAD) { resp_status_only(resp, 405, "Method Not Allowed"); return; }
        resp_asset(resp, "application/javascript; charset=utf-8", IDE_PICOVM_JS, IDE_PICOVM_JS_LEN, method == M_HEAD);
        return;
    }
    if (rest_len == 19 && memcmp(rest, "baremetal-binary.js", 19) == 0) {
        if (method != M_GET && method != M_HEAD) { resp_status_only(resp, 405, "Method Not Allowed"); return; }
        resp_asset(resp, "application/javascript; charset=utf-8", IDE_BAREMETAL_BINARY_JS, IDE_BAREMETAL_BINARY_JS_LEN, method == M_HEAD);
        return;
    }
    if (rest_len == 6 && memcmp(rest, "config", 6) == 0) {
        dispatch_config(method, resp);
        return;
    }
    if (rest_len > 5 && memcmp(rest, "card/", 5) == 0) {
        dispatch_card(method, path, path_len, rest + 5, rest_len - 5,
                     body, body_len, cookie, cookie_len, has_pw_auth_header,
                     write_token, write_token_len,
                     tenant_id, tenant_id_len, is_partition_hop, resp);
        return;
    }

    resp_status_only(resp, 404, "Not Found");
}
