#ifndef METAL_IDE_ASSETS_H
#define METAL_IDE_ASSETS_H

/* ide_assets.c is GENERATED by tools/gen_ide_assets.py from:
 *   - ../picoscript/docs/index.html (the ACTUAL upstream PicoScript WebIDE
 *     portal, vendored verbatim, with tools/ide_server_bridge.js injected
 *     before </body> -- see IDE_HTML below)
 *   - tools/ide_picowal_workspace.html (this repo's own PicoWAL workspace
 *     page -- see IDE_PICOWAL_HTML below)
 *   - ../picoscript/vm/pico_hooks.js
 *   - ../picoscript/vm/picoc.js
 *   - ../picoscript/vm/picovm.js
 *   - ../baremetaljstools/src/BareMetal.Binary.js (vendored byte-for-byte,
 *     never modified -- BSO1 fast-serialization codec for the PicoWAL
 *     workspace's "Fast Serial (BSO1)" panel)
 *
 * src/ide_assets.c is committed so a normal `make` never needs the sibling
 * picoscript/baremetaljstools checkouts at runtime or build time.
 * Regenerate with `make gen-ide-assets` (requires python3 and
 * ../picoscript + ../baremetaljstools). */

#include <stddef.h>

extern const char   IDE_HTML[];
extern const size_t IDE_HTML_LEN;

extern const char   IDE_PICOWAL_HTML[];
extern const size_t IDE_PICOWAL_HTML_LEN;

extern const char   IDE_PICO_HOOKS_JS[];
extern const size_t IDE_PICO_HOOKS_JS_LEN;

extern const char   IDE_PICOC_JS[];
extern const size_t IDE_PICOC_JS_LEN;

extern const char   IDE_PICOVM_JS[];
extern const size_t IDE_PICOVM_JS_LEN;

extern const char   IDE_BAREMETAL_BINARY_JS[];
extern const size_t IDE_BAREMETAL_BINARY_JS_LEN;

#endif
